fix: correct tls-client version to 1.0.1 (max available)
ERROR: Previous version specified tls-client>=1.10.0 but max available is 1.0.1
SOLUTION: Changed to tls-client==1.0.1

Available tls-client versions:
- 0.0.1, 0.0.2, ..., 0.0.10
- 0.1.0, 0.1.1, ..., 0.1.9
- 0.2, 0.2.1, 0.2.2
- 1.0, 1.0.1 (LATEST)

This fixes the Docker build failure in Coolify